In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("surat_uncleaned.csv")

In [5]:
df["BHK"] = df["property_name"].str.extract(r'(\d+)\s*BHK').astype(float)

In [12]:
df["Location"] = df["property_name"].str.extract(r'in\s+([\w\s]+)$',expand = False).str.strip()

In [14]:
df["area_type"] = df["areaWithType"].map({
    'Carpet Area' : 1,
    'Super Area' : 2}).fillna(0).astype(int)

In [17]:
df["area_sqft"] = df["square_feet"].str.extract(r'(\d+)').astype(float)

In [20]:
df["transaction_type"] = df["transaction"].map({
    'New Property' : 1,
    'Resale' : 2}).fillna(0).astype(int)

In [22]:
df["ready_to_move"] = df["status"].apply(lambda x: 1 if 'Ready to Move' in str(x) else 0)

In [24]:
df["furnishing_level"] = df["furnishing"].map({
    'Unfurnished' : 0,
    'Semi-Furnished' : 1,
    'Fully Furnished' : 2}).fillna(0).astype(int)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,BHK,Location,area_type,area_sqft,transaction_type,ready_to_move,furnishing_level
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac,2.0,Dindoli Surat,1,644.0,1,0,0
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac,2.0,Althan Surat,2,1278.0,1,0,0
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac,2.0,Pal Gam Surat,2,1173.0,2,1,1
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac,2.0,Jahangirabad Surat,1,700.0,1,1,0
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac,2.0,NaN,2,1250.0,0,0,0

In [26]:
df["facing"] = df["facing"].astype('category').cat.codes

In [31]:
df['price_per_sqft'] = df['price_per_sqft'].str.replace('₹', '', regex=False)\
                                           .str.replace('per sqft', '', regex=False)\
                                           .str.replace(',', '', regex=False)\
                                           .astype(float)

In [32]:
df.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,BHK,Location,area_type,area_sqft,transaction_type,ready_to_move,furnishing_level
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,173,"Luxury project with basement parking, Solar ro...",2891.0,₹33.8 Lac,2.0,Dindoli Surat,1,644.0,1,0,0
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,156,2 And 3 BHK Luxurious Flat for Sell In New Alt...,3551.0,₹45.4 Lac,2.0,Althan Surat,2,1278.0,1,0,0
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,54,This affordable 2 BHK flat is situated along a...,3800.0,₹44.6 Lac,2.0,Pal Gam Surat,2,1173.0,2,1,1
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,54,2 BHK Flat For sell IN Jahangirabad Prime Loca...,3966.0,₹47 Lac,2.0,Jahangirabad Surat,1,700.0,1,1,0
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,12,"Multistorey Apartment for Sale in Palanpur, Su...",3600.0,₹45 Lac,2.0,NaN,2,1250.0,0,0,0

In [37]:
def convert_price(p):
    if pd.isna(p):
        return np.nan
    p = p.replace('₹', '').replace(',', '').strip()
    if 'Lac' in p:
        return float(p.replace('Lac', '').strip()) * 1e5
    elif 'Cr' in p:
        return float(p.replace('Cr', '').strip()) * 1e7
    else:
        try:
            return float(p)
        except:
            return np.nan

In [38]:
df['price_rs'] = df['price'].apply(convert_price)

In [47]:
df =  df.drop(columns=['price'])

In [56]:
df = df.dropna()

In [62]:
df.to_csv("cleaned_data.csv",index = False)

<class 'pandas.core.frame.DataFrame'>
Index: 1921 entries, 0 to 4398
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   facing            1921 non-null   int16
 1   price_per_sqft    1921 non-null   float64
 2   BHK               1921 non-null   float64
 3   Location          1921 non-null   object
 4   area_type         1921 non-null   int64
 5   area_sqft         1921 non-null   float64
 6   transaction_type  1921 non-null   int64
 7   ready_to_move     1921 non-null   int64
 8   furnishing_level  1921 non-null   int64
 9   price_rs          1921 non-null   float64
dtypes: float64(4), int16(1), int64(4), object(1)
memory usage: 153.8+ KB